# Generated by Django 5.1.6 on 2025-02-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=255)),
                ('graduate_type', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=10)),
                ('degree', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('director_email', models.EmailField(max_length=254)),
                ('deputy_director', models.CharField(max_length=255)),
                ('deputy_email', models.EmailField(max_length=254)),
                ('hod', models.CharField(max_length=255)),
                ('hod_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
