# Generated by Django 5.1.6 on 2025-02-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_designationdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignationDetails',
        ),
    ]
