# Generated by Django 5.1.6 on 2025-02-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_delete_designationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate', models.CharField(choices=[('UG', 'UG (Undergraduate)'), ('PG', 'PG (Postgraduate)')], max_length=2)),
                ('degree', models.CharField(choices=[('BBA', 'BBA'), ('BMS', 'BMS'), ('MBA', 'MBA')], max_length=3)),
                ('campus', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=254)),
                ('deputy_director', models.CharField(blank=True, max_length=100, null=True)),
                ('deputy_mailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('hod', models.CharField(max_length=100)),
                ('hod_mailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
