# Generated by Django 5.1.6 on 2025-03-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_department_event_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
