# Generated by Django 5.1.6 on 2025-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_event_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='academicevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='classinfo',
            old_name='display_name',
            new_name='description',
        ),
    ]
