# Generated by Django 5.1.6 on 2025-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_academicevents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicevents',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
