# Generated by Django 5.1.6 on 2025-03-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_calendarevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevents',
            old_name='department_center',
            new_name='faculty',
        ),
    ]
