# Generated by Django 5.1.6 on 2025-03-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_eventcalendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eventcalendar',
        ),
    ]
