# Generated by Django 5.1.6 on 2025-03-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_eventcalendar_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='jainevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('faculty', models.CharField(choices=[('engineering', 'Faculty of Engineering and Technology'), ('arts_humanities', 'Faculty of Arts, Humanities and Social Sciences'), ('basic_applied_sciences', 'Faculty of Basic and Applied Sciences'), ('commerce', 'Faculty of Commerce'), ('management', 'Faculty of Management Studies'), ('creativity_design', 'Faculty of Creativity and Design')], max_length=50)),
                ('venue', models.CharField(max_length=255)),
                ('coordinator', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='event_pdfs/')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
