# Generated by Django 5.1.6 on 2025-03-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_alter_jainevent_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScienceEng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('School of Computer Science and Engineering', 'School of Computer Science and Engineering')], max_length=100)),
                ('department', models.CharField(choices=[('Department of Computer Science and Engineering', 'Department of Computer Science and Engineering')], max_length=100)),
                ('location', models.CharField(choices=[('bangalore', 'Bangalore'), ('kochi', 'Kochi')], max_length=100)),
                ('graduation', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate')], max_length=100)),
                ('degree', models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech')], max_length=100)),
                ('director_name', models.CharField(blank=True, max_length=100, null=True)),
                ('director_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deputy_director_name', models.CharField(blank=True, max_length=100, null=True)),
                ('deputy_director_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hod_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('student_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
