# Generated by Django 5.1.6 on 2025-03-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_computerscienceandengineering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='computerscienceandengineering',
            name='specialization',
        ),
        migrations.AddField(
            model_name='computerscienceandengineering',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='academic.specialization'),
        ),
    ]
