# Generated by Django 5.1.6 on 2025-03-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JainEventCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('Faculty of Engineering and Technology', 'Faculty of Engineering and Technology'), ('Faculty of Arts, Humanities and Social Sciences', 'Faculty of Arts, Humanities and Social Sciences'), ('Faculty of Basic and Applied Sciences', 'Faculty of Basic and Applied Sciences'), ('Faculty of Commerce', 'Faculty of Commerce'), ('Faculty of Management Studies', 'Faculty of Management Studies'), ('Faculty of Creativity and Design', 'Faculty of Creativity and Design')], max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event_description', models.TextField()),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=50)),
                ('event_coordinator', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=255)),
            ],
        ),
    ]
