# Generated by Django 5.1.7 on 2025-03-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_module_delete_jaineventcalendar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='modulelist',
        ),
    ]
