# Generated by Django 5.1.7 on 2025-03-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_rename_name_module_modulelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='modules_pdfs/'),
        ),
        migrations.AddField(
            model_name='module',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
