# Generated by Django 5.1.7 on 2025-03-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_module_pdf_module_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='module',
            name='submitted_by',
        ),
        migrations.CreateModel(
            name='ModuleYearPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='modules_pdfs/')),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_pdfs', to='academic.module')),
            ],
        ),
    ]
