# Generated by Django 5.1.6 on 2025-02-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=547167, unique=True),
        ),
    ]
