# Generated by Django 5.1.7 on 2025-03-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=126312, unique=True),
        ),
    ]
